### ISSUE TITLE
TODO list until "release"

### ISSUE THREAD

**Issue by freezy** [freezy/node-pind#1]
- [x] Fix session handling when server restarts and client reconnects
- [x] Secure server-side RPC calls
- [x] Fix table details page (fix, not finalize)
- [x] Add layouts for non-data pages
- [x] Test and fix bugs when logged as non-admin
- [x] Fix leaderboard on main page
- [x] Fix coin drop page
- [x] Update website
- [x] Add "Check Config" button that validates `settings-mine.js`
